# LED endpoint base paths
LED_ENDPOINT_BASE_PATH = "/led"
LED_ID = "/<led_id>"

# LED actions
LED_ACTION_ON = "/on"
LED_ACTION_OFF = "/off"
LED_ACTION_TOGGLE = "/toggle"

# LED status
LED_STATUS_ON = "ON"
LED_STATUS_OFF = "OFF"

# PING endpoint
PING_ENDPOINT_BASE_PATH = "/ping"
# Enumeration endpoint
ENUMERATION_ENDPOINT_BASE_PATH = "/enumerate"
# Events endpoint
EVENTS_ENDPOINT_BASE_PATH = "/events"

# Event messages
EVENT_LED_TOGGLE = "LED_TOGGLE"
EVENT_LED_COLOR_SWITCH = "LED_COLOR_SWITCH"
EVENT_PING_BOARD = "PING_BOARD"
EVENT_SENSOR_TRIGGER = "SENSOR_TRIGGER"